/**
 * Centralized SEO Keyword Strategy for Adaah (https://adaah.life)
 * Target Market: Hyderabad, Telangana, India
 * 
 * Rules:
 * - Natural, contextual usage strictly adhering to search intent.
 * - Supports BOTH "Escort" and "Call Girl" search term clusters seamlessly.
 * - Zero keyword stuffing, zero explicit phrases, zero fake claims.
 * - All content represents consenting adults aged 18+.
 */

export const KEYWORD_STRATEGY = {
  brand: {
    primary: 'Adaah',
    full: 'Adaah Hyderabad 18+ Private Directory',
    navigational: ['Adaah', 'Adaah Hyderabad', 'Adaah directory', 'Adaah life'],
  },

  homepage: {
    primaryH1: "Hyderabad's 18+ Private Directory",
    suggestedTitle: 'Adaah | Hyderabad 18+ Private Directory',
    suggestedDescription:
      'Explore Adaah, a Hyderabad-focused 18+ private directory featuring location-based listings, verified companion profiles, escort services and useful guides in Banjara Hills, Jubilee Hills, Gachibowli and Hitech City.',
    targetKeywords: [
      'Hyderabad 18+ private directory',
      'Hyderabad escorts',
      'escorts in Hyderabad',
      'Hyderabad escort service',
      'Hyderabad escort directory',
      'Hyderabad call girls',
      'call girls in Hyderabad',
      'Hyderabad call girl directory',
      'Hyderabad private directory',
      'Hyderabad companion directory',
      'Hyderabad private profiles',
      'Hyderabad adult directory',
    ],
  },

  profilesListing: {
    primaryH1: 'Hyderabad Escort & Call Girl Profiles | 18+ Directory',
    suggestedTitle: 'Hyderabad Call Girl Profiles & Escorts | 18+ Directory | Adaah',
    suggestedDescription:
      'Browse verified Hyderabad escort profiles, call girl listings and independent 18+ companion listings with transparent rate guidelines, availability badges, and discreet contact.',
    targetKeywords: [
      'Hyderabad escort profiles',
      'Hyderabad escorts',
      'escorts in Hyderabad',
      'Hyderabad call girl profiles',
      'Hyderabad call girl listings',
      'Hyderabad private profiles',
      'Hyderabad 18+ profiles',
      'Hyderabad adult profiles',
      'Hyderabad profile directory',
      'Hyderabad companion profiles',
    ],
  },

  locationsListing: {
    primaryH1: 'Hyderabad Location Directories & Neighborhood Profiles',
    suggestedTitle: 'Hyderabad Location Directories | 18+ Profiles | Adaah',
    suggestedDescription:
      'Explore verified 18+ directory listings across Banjara Hills, Jubilee Hills, Gachibowli, Hitech City, Madhapur, Kondapur and 30 Hyderabad areas.',
    targetKeywords: [
      'Hyderabad location directory',
      'Hyderabad escort locations',
      'Hyderabad call girl locations',
      'Hyderabad neighborhood companion directory',
      'Banjara Hills to Gachibowli directory',
      'Hyderabad area directory',
    ],
  },

  /**
   * Dedicated Escort Keyword Cluster (Active & Maintained)
   */
  escortKeywords: {
    core: [
      'Hyderabad escorts',
      'escorts in Hyderabad',
      'Hyderabad escort',
      'escort in Hyderabad',
      'Hyderabad escort service',
      'escort service Hyderabad',
      'Hyderabad escort services',
      'Hyderabad escort directory',
      'Hyderabad escort profiles',
      'Hyderabad escort listings',
    ],
    directory: [
      'Hyderabad escort directory',
      'escort directory Hyderabad',
      'Hyderabad escort listings',
      'escort listings Hyderabad',
      'Hyderabad escort profiles',
      'escort profiles Hyderabad',
    ],
    profile: [
      'Hyderabad escort profiles',
      'Hyderabad escort listings',
      'independent escorts Hyderabad',
      'VIP escorts Hyderabad',
    ],
    service: [
      'Hyderabad escort service',
      'escort service in Hyderabad',
      'Hyderabad escort services',
    ],
    longTail: [
      'verified escorts Hyderabad',
      'independent escorts Hyderabad',
      'Banjara Hills escorts',
      'Jubilee Hills escorts',
      'Gachibowli escorts',
      'Hitech City escorts',
      'Madhapur escorts',
      'Kondapur escorts',
      'Begumpet escorts',
      'Secunderabad escorts',
      'Somajiguda escorts',
    ],
  },

  /**
   * Dedicated Call Girl Keyword Cluster (Active & Maintained)
   */
  callGirlKeywords: {
    core: [
      'call girls Hyderabad',
      'Hyderabad call girls',
      'call girl Hyderabad',
      'call girl in Hyderabad',
      'call girls in Hyderabad',
      'Hyderabad call girl service',
      'call girl service Hyderabad',
      'call girl services Hyderabad',
      'Hyderabad call girl directory',
      'Hyderabad call girl profiles',
      'Hyderabad call girl listings',
    ],
    directory: [
      'Hyderabad call girl directory',
      'call girl directory Hyderabad',
      'Hyderabad call girl listings',
      'call girl listings Hyderabad',
      'Hyderabad call girl profiles',
      'call girl profiles Hyderabad',
      'Hyderabad private directory',
      'Hyderabad adult directory',
      'Hyderabad 18+ directory',
    ],
    profile: [
      'Hyderabad call girl profiles',
      'Hyderabad call girl listings',
      'Hyderabad private profiles',
      'Hyderabad 18+ profiles',
      'Hyderabad adult profiles',
      'Hyderabad profile directory',
    ],
    service: [
      'Hyderabad call girl service',
      'call girl service Hyderabad',
      'Hyderabad private directory services',
      'call girl services in Hyderabad',
    ],
    locationClusterPattern: {
      patternPrimary: '[location] call girls',
      patternInLocation: 'call girls in [location]',
      patternService: '[location] call girl service',
      patternDirectory: '[location] call girl directory',
      patternProfiles: '[location] call girl profiles',
      patternPrivateDir: '[location] private directory',
      patternAgeDir: '[location] 18+ directory',
    },
    longTail: [
      'verified call girls Hyderabad',
      'independent call girls Hyderabad',
      'Banjara Hills call girls',
      'Jubilee Hills call girls',
      'Gachibowli call girls',
      'Hitech City call girls',
      'Madhapur call girls',
      'Kondapur call girls',
      'Begumpet call girls',
      'Secunderabad call girls',
      'Somajiguda call girls',
    ],
  },

  /**
   * Location Specific SEO Clusters (Supporting BOTH Escorts & Call Girls)
   */
  locationClusters: {
    'banjara-hills': {
      primary: 'Banjara Hills call girls',
      title: 'Banjara Hills Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Banjara Hills 18+ Private Directory',
      secondary: [
        'Banjara Hills call girls',
        'call girls in Banjara Hills',
        'Banjara Hills escorts',
        'escorts in Banjara Hills',
        'Banjara Hills escort service',
        'Banjara Hills call girl service',
        'Banjara Hills call girl directory',
        'Banjara Hills call girl profiles',
        'Banjara Hills private directory',
        'Banjara Hills 18+ directory',
      ],
      relatedAreas: ['jubilee-hills', 'somajiguda', 'punjagutta', 'khairatabad'],
    },
    'jubilee-hills': {
      primary: 'Jubilee Hills call girls',
      title: 'Jubilee Hills Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Jubilee Hills 18+ Private Directory',
      secondary: [
        'Jubilee Hills call girls',
        'call girls in Jubilee Hills',
        'Jubilee Hills escorts',
        'escorts in Jubilee Hills',
        'Jubilee Hills escort service',
        'Jubilee Hills call girl service',
        'Jubilee Hills call girl directory',
        'Jubilee Hills call girl profiles',
        'Jubilee Hills private directory',
      ],
      relatedAreas: ['banjara-hills', 'madhapur', 'gachibowli', 'hitech-city'],
    },
    'gachibowli': {
      primary: 'Gachibowli call girls',
      title: 'Gachibowli Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Gachibowli 18+ Private Directory',
      secondary: [
        'Gachibowli call girls',
        'call girls in Gachibowli',
        'Gachibowli escorts',
        'escorts in Gachibowli',
        'Gachibowli escort service',
        'Gachibowli call girl service',
        'Gachibowli call girl directory',
        'Gachibowli call girl profiles',
        'Gachibowli private directory',
      ],
      relatedAreas: ['financial-district', 'nanakramguda', 'kondapur', 'madhapur', 'hitech-city'],
    },
    'hitech-city': {
      primary: 'Hitech City call girls',
      title: 'Hitech City Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Hitech City 18+ Private Directory',
      secondary: [
        'Hitech City call girls',
        'call girls in Hitech City',
        'Hitech City escorts',
        'escorts in Hitech City',
        'Hitech City escort service',
        'Hitech City call girl service',
        'Hitech City call girl directory',
        'Hitech City call girl profiles',
      ],
      relatedAreas: ['madhapur', 'gachibowli', 'kondapur', 'raidurg'],
    },
    'madhapur': {
      primary: 'Madhapur call girls',
      title: 'Madhapur Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Madhapur 18+ Private Directory',
      secondary: [
        'Madhapur call girls',
        'call girls in Madhapur',
        'Madhapur escorts',
        'escorts in Madhapur',
        'Madhapur escort service',
        'Madhapur call girl service',
        'Madhapur call girl directory',
        'Madhapur call girl profiles',
      ],
      relatedAreas: ['hitech-city', 'jubilee-hills', 'kondapur', 'gachibowli'],
    },
    'kondapur': {
      primary: 'Kondapur call girls',
      title: 'Kondapur Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Kondapur 18+ Private Directory',
      secondary: [
        'Kondapur call girls',
        'call girls in Kondapur',
        'Kondapur escorts',
        'escorts in Kondapur',
        'Kondapur escort service',
        'Kondapur call girl service',
        'Kondapur call girl directory',
        'Kondapur call girl profiles',
      ],
      relatedAreas: ['gachibowli', 'madhapur', 'hitech-city', 'financial-district'],
    },
    'begumpet': {
      primary: 'Begumpet call girls',
      title: 'Begumpet Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Begumpet 18+ Private Directory',
      secondary: [
        'Begumpet call girls',
        'call girls in Begumpet',
        'Begumpet escorts',
        'escorts in Begumpet',
        'Begumpet escort service',
        'Begumpet call girl service',
        'Begumpet call girl directory',
        'Begumpet call girl profiles',
      ],
      relatedAreas: ['somajiguda', 'punjagutta', 'ameerpet', 'secunderabad'],
    },
    'secunderabad': {
      primary: 'Secunderabad call girls',
      title: 'Secunderabad Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Secunderabad 18+ Private Directory',
      secondary: [
        'Secunderabad call girls',
        'call girls in Secunderabad',
        'Secunderabad escorts',
        'escorts in Secunderabad',
        'Secunderabad escort service',
        'Secunderabad call girl service',
        'Secunderabad call girl directory',
        'Secunderabad call girl profiles',
      ],
      relatedAreas: ['begumpet', 'tarnaka', 'sainikpuri', 'himayatnagar'],
    },
    'somajiguda': {
      primary: 'Somajiguda call girls',
      title: 'Somajiguda Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Somajiguda 18+ Private Directory',
      secondary: [
        'Somajiguda call girls',
        'call girls in Somajiguda',
        'Somajiguda escorts',
        'escorts in Somajiguda',
        'Somajiguda escort service',
        'Somajiguda call girl service',
        'Somajiguda call girl directory',
        'Somajiguda call girl profiles',
      ],
      relatedAreas: ['banjara-hills', 'punjagutta', 'khairatabad', 'begumpet'],
    },
    'ameerpet': {
      primary: 'Ameerpet call girls',
      title: 'Ameerpet Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Ameerpet 18+ Private Directory',
      secondary: ['Ameerpet call girls', 'call girls in Ameerpet', 'Ameerpet escorts', 'Ameerpet call girl service'],
      relatedAreas: ['begumpet', 'punjagutta', 'somajiguda'],
    },
    'punjagutta': {
      primary: 'Punjagutta call girls',
      title: 'Punjagutta Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Punjagutta 18+ Private Directory',
      secondary: ['Punjagutta call girls', 'call girls in Punjagutta', 'Punjagutta escorts', 'Punjagutta call girl service'],
      relatedAreas: ['banjara-hills', 'somajiguda', 'ameerpet'],
    },
    'himayatnagar': {
      primary: 'Himayatnagar call girls',
      title: 'Himayatnagar Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Himayatnagar 18+ Private Directory',
      secondary: ['Himayatnagar call girls', 'call girls in Himayatnagar', 'Himayatnagar escorts', 'Himayatnagar call girl service'],
      relatedAreas: ['secunderabad', 'khairatabad', 'masab-tank'],
    },
    'kukatpally': {
      primary: 'Kukatpally call girls',
      title: 'Kukatpally Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Kukatpally 18+ Private Directory',
      secondary: ['Kukatpally call girls', 'call girls in Kukatpally', 'Kukatpally escorts', 'Kukatpally call girl service'],
      relatedAreas: ['kondapur', 'hitech-city', 'madhapur'],
    },
    'manikonda': {
      primary: 'Manikonda call girls',
      title: 'Manikonda Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Manikonda 18+ Private Directory',
      secondary: ['Manikonda call girls', 'call girls in Manikonda', 'Manikonda escorts', 'Manikonda call girl service'],
      relatedAreas: ['gachibowli', 'narsingi', 'financial-district'],
    },
    'mehdipatnam': {
      primary: 'Mehdipatnam call girls',
      title: 'Mehdipatnam Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Mehdipatnam 18+ Private Directory',
      secondary: ['Mehdipatnam call girls', 'call girls in Mehdipatnam', 'Mehdipatnam escorts', 'Mehdipatnam call girl service'],
      relatedAreas: ['masab-tank', 'tolichowki', 'attapur'],
    },
    'masab-tank': {
      primary: 'Masab Tank call girls',
      title: 'Masab Tank Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Masab Tank 18+ Private Directory',
      secondary: ['Masab Tank call girls', 'call girls in Masab Tank', 'Masab Tank escorts', 'Masab Tank call girl service'],
      relatedAreas: ['banjara-hills', 'mehdipatnam', 'khairatabad'],
    },
    'khairatabad': {
      primary: 'Khairatabad call girls',
      title: 'Khairatabad Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Khairatabad 18+ Private Directory',
      secondary: ['Khairatabad call girls', 'call girls in Khairatabad', 'Khairatabad escorts', 'Khairatabad call girl service'],
      relatedAreas: ['somajiguda', 'banjara-hills', 'masab-tank'],
    },
    'sainikpuri': {
      primary: 'Sainikpuri call girls',
      title: 'Sainikpuri Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Sainikpuri 18+ Private Directory',
      secondary: ['Sainikpuri call girls', 'call girls in Sainikpuri', 'Sainikpuri escorts', 'Sainikpuri call girl service'],
      relatedAreas: ['secunderabad', 'tarnaka', 'kompally'],
    },
    'kompally': {
      primary: 'Kompally call girls',
      title: 'Kompally Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Kompally 18+ Private Directory',
      secondary: ['Kompally call girls', 'call girls in Kompally', 'Kompally escorts', 'Kompally call girl service'],
      relatedAreas: ['secunderabad', 'sainikpuri', 'kukatpally'],
    },
    'financial-district': {
      primary: 'Financial District call girls',
      title: 'Financial District Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Financial District 18+ Private Directory',
      secondary: ['Financial District call girls', 'call girls in Financial District', 'Financial District escorts', 'Financial District call girl service'],
      relatedAreas: ['gachibowli', 'nanakramguda', 'narsingi', 'raidurg'],
    },
    'nanakramguda': {
      primary: 'Nanakramguda call girls',
      title: 'Nanakramguda Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Nanakramguda 18+ Private Directory',
      secondary: ['Nanakramguda call girls', 'call girls in Nanakramguda', 'Nanakramguda escorts', 'Nanakramguda call girl service'],
      relatedAreas: ['financial-district', 'gachibowli', 'raidurg'],
    },
    'raidurg': {
      primary: 'Raidurg call girls',
      title: 'Raidurg Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Raidurg 18+ Private Directory',
      secondary: ['Raidurg call girls', 'call girls in Raidurg', 'Raidurg escorts', 'Raidurg call girl service'],
      relatedAreas: ['hitech-city', 'gachibowli', 'financial-district'],
    },
    'narsingi': {
      primary: 'Narsingi call girls',
      title: 'Narsingi Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Narsingi 18+ Private Directory',
      secondary: ['Narsingi call girls', 'call girls in Narsingi', 'Narsingi escorts', 'Narsingi call girl service'],
      relatedAreas: ['manikonda', 'financial-district', 'gachibowli'],
    },
    'tolichowki': {
      primary: 'Tolichowki call girls',
      title: 'Tolichowki Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Tolichowki 18+ Private Directory',
      secondary: ['Tolichowki call girls', 'call girls in Tolichowki', 'Tolichowki escorts', 'Tolichowki call girl service'],
      relatedAreas: ['mehdipatnam', 'banjara-hills', 'jubilee-hills'],
    },
    'attapur': {
      primary: 'Attapur call girls',
      title: 'Attapur Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Attapur 18+ Private Directory',
      secondary: ['Attapur call girls', 'call girls in Attapur', 'Attapur escorts', 'Attapur call girl service'],
      relatedAreas: ['mehdipatnam', 'narsingi', 'masab-tank'],
    },
    'tarnaka': {
      primary: 'Tarnaka call girls',
      title: 'Tarnaka Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Tarnaka 18+ Private Directory',
      secondary: ['Tarnaka call girls', 'call girls in Tarnaka', 'Tarnaka escorts', 'Tarnaka call girl service'],
      relatedAreas: ['secunderabad', 'uppal', 'sainikpuri'],
    },
    'uppal': {
      primary: 'Uppal call girls',
      title: 'Uppal Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Uppal 18+ Private Directory',
      secondary: ['Uppal call girls', 'call girls in Uppal', 'Uppal escorts', 'Uppal call girl service'],
      relatedAreas: ['lb-nagar', 'tarnaka', 'dilsukhnagar'],
    },
    'lb-nagar': {
      primary: 'LB Nagar call girls',
      title: 'LB Nagar Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'LB Nagar 18+ Private Directory',
      secondary: ['LB Nagar call girls', 'call girls in LB Nagar', 'LB Nagar escorts', 'LB Nagar call girl service'],
      relatedAreas: ['dilsukhnagar', 'uppal', 'attapur'],
    },
    'dilsukhnagar': {
      primary: 'Dilsukhnagar call girls',
      title: 'Dilsukhnagar Call Girls & Escorts | 18+ Directory | Adaah',
      h1: 'Dilsukhnagar 18+ Private Directory',
      secondary: ['Dilsukhnagar call girls', 'call girls in Dilsukhnagar', 'Dilsukhnagar escorts', 'Dilsukhnagar call girl service'],
      relatedAreas: ['lb-nagar', 'himayatnagar', 'uppal'],
    },
  },

  categories: {
    primaryH1: 'Companion Categories & Specialties in Hyderabad',
    targetKeywords: [
      'independent escorts Hyderabad',
      'VIP escorts Hyderabad',
      'models Hyderabad',
      'travel companions Hyderabad',
      'dinner companions Hyderabad',
      'event companions Hyderabad',
    ],
  },

  services: {
    primaryH1: 'Companionship Services & Occasions in Hyderabad',
    targetKeywords: [
      'Hyderabad escort service',
      'Hyderabad call girl service',
      'dinner date accompaniment Hyderabad',
      'VIP social companionship Hyderabad',
      'luxury travel partner Hyderabad',
      'hotel suite outcall Hyderabad',
      'incall appointment Hyderabad',
      'overnight companionship Hyderabad',
    ],
  },

  guides: {
    primaryH1: 'Hyderabad Editorial Guides, Discretion & Safety',
    targetKeywords: [
      'Hyderabad companion booking etiquette',
      'online directory safety Hyderabad',
      'privacy protection Hyderabad directory',
      'identifying verified profiles',
      'hotel suite outcall safety guide',
    ],
  },
};
