export const SEO_CONFIG = {
  siteName: 'Adaah',
  fullName: 'Adaah — Hyderabad 18+ Private Directory',
  siteUrl: (typeof process !== 'undefined' && (process.env as any)?.NEXT_PUBLIC_SITE_URL) || (import.meta as any).env?.VITE_SITE_URL || 'https://adaah.life',
  defaultTitle: 'Adaah | Hyderabad 18+ Private Directory',
  titleTemplate: '%s | Adaah',
  defaultDescription:
    'Explore Adaah, a premier Hyderabad-focused 18+ private directory featuring location-based listings, verified companion profiles, services and discretion guides in Banjara Hills, Jubilee Hills, Gachibowli, and Hitech City.',
  defaultImage: 'https://adaah.life/images/profiles/profile-001.webp',
  locale: 'en_IN',
  language: 'en-IN',
  country: 'IN',
  city: 'Hyderabad',
  state: 'Telangana',
  twitterHandle: undefined, // Add official handle if available
  googleSiteVerification: (typeof process !== 'undefined' && (process.env as any)?.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION) || (import.meta as any).env?.VITE_GOOGLE_SITE_VERIFICATION || '',
  googleAnalyticsId: (typeof process !== 'undefined' && (process.env as any)?.NEXT_PUBLIC_GA_ID) || (import.meta as any).env?.VITE_GA_ID || '',

  organization: {
    name: 'Adaah',
    url: 'https://adaah.life',
    logo: 'https://adaah.life/favicon.png',
    description: 'Premier 18+ private directory focused on Hyderabad, Telangana, India.',
    address: {
      addressLocality: 'Hyderabad',
      addressRegion: 'Telangana',
      addressCountry: 'IN',
    },
    contactPoint: {
      telephone: '+91 89993 84340',
      contactType: 'customer service',
      areaServed: 'IN',
      availableLanguage: ['en', 'hi', 'te'],
    },
  },

  primaryLocations: [
    'Banjara Hills',
    'Jubilee Hills',
    'Gachibowli',
    'Hitech City',
    'Madhapur',
    'Kondapur',
    'Begumpet',
    'Secunderabad',
    'Somajiguda',
    'Ameerpet',
    'Punjagutta',
    'Himayatnagar',
    'Kukatpally',
    'Manikonda',
    'Mehdipatnam',
    'Masab Tank',
    'Khairatabad',
    'Sainikpuri',
    'Kompally',
    'Financial District',
    'Nanakramguda',
    'Raidurg',
    'Narsingi',
    'Tolichowki',
    'Attapur',
    'Tarnaka',
    'Uppal',
    'LB Nagar',
    'Dilsukhnagar',
  ],
};
