export const siteConfig = {
  name: 'Adaah',
  fullName: 'Adaah — 18+ Private Directory',
  tagline: '18+ Private Directory',
  description:
    'Browse verified adult profiles, explore Hyderabad metropolitan locations, and discover discreet companionship services across India.',
  url: 'https://adaah-directory.com',
  ogImage: '/images/profiles/profile-001.webp',
  contact: {
    phone: '+91 89993 84340',
    phoneFormatted: '+91 89993 84340',
    phoneRaw: '918999384340',
    phoneTel: 'tel:+918999384340',
    whatsapp: 'https://wa.me/918999384340',
    whatsappUrl: 'https://wa.me/918999384340',
    whatsappRaw: '918999384340',
    defaultWhatsAppMessage: 'Hello Adaah Concierge, I would like to make an inquiry.',
    email: 'concierge@adaah-directory.com',
    supportPhone: '+91 89993 84340',
    address: 'Banjara Hills & Jubilee Hills, Hyderabad, India',
    workingHours: 'Daily, 10:00 AM – 02:00 AM IST',
  },
  navigation: {
    mainNav: [
      { title: 'Profiles', href: '/profiles' },
      { title: 'Categories', href: '/categories', hasDropdown: true },
      { title: 'Locations', href: '/locations', hasDropdown: true },
      { title: 'Services', href: '/services' },
      { title: 'Guides', href: '/guides' },
      { title: 'FAQ', href: '/faq' },
    ],
    categoriesDropdown: [
      { title: 'Independent Companions', href: '/categories/independent-companions' },
      { title: 'Models', href: '/categories/models' },
      { title: 'VIP Companions', href: '/categories/vip-companions' },
      { title: 'Travel Companions', href: '/categories/travel-companions' },
      { title: 'Dinner Companions', href: '/categories/dinner-companions' },
      { title: 'Event Companions', href: '/categories/event-companions' },
    ],
    locationsDropdown: [
      { title: 'Banjara Hills', href: '/locations/banjara-hills' },
      { title: 'Jubilee Hills', href: '/locations/jubilee-hills' },
      { title: 'Gachibowli', href: '/locations/gachibowli' },
      { title: 'Hitech City', href: '/locations/hitech-city' },
      { title: 'Madhapur', href: '/locations/madhapur' },
      { title: 'Kondapur', href: '/locations/kondapur' },
      { title: 'Begumpet', href: '/locations/begumpet' },
      { title: 'Secunderabad', href: '/locations/secunderabad' },
      { title: 'Somajiguda', href: '/locations/somajiguda' },
    ],
    hyderabadLocations: [
      { title: 'Banjara Hills', href: '/locations/banjara-hills' },
      { title: 'Jubilee Hills', href: '/locations/jubilee-hills' },
      { title: 'Gachibowli', href: '/locations/gachibowli' },
      { title: 'Hitech City', href: '/locations/hitech-city' },
      { title: 'Madhapur', href: '/locations/madhapur' },
      { title: 'Kondapur', href: '/locations/kondapur' },
      { title: 'Begumpet', href: '/locations/begumpet' },
      { title: 'Secunderabad', href: '/locations/secunderabad' },
      { title: 'Somajiguda', href: '/locations/somajiguda' },
    ],
    footerNav: {
      directory: [
        { title: 'Profiles', href: '/profiles' },
        { title: 'Categories', href: '/categories' },
        { title: 'Locations', hrewhatsappUrlf: '/locations' },
        { title: 'Services', href: '/services' },
      ],
      resources: [
        { title: 'Guides & Etiquette', href: '/guides' },
        { title: 'FAQ', href: '/faq' },
        { title: 'Safety & Discretion', href: '/safety' },
      ],
      company: [
        { title: 'About Adaah', href: '/about' },
        { title: 'Contact Concierge', href: '/contact' },
      ],
      legal: [
        { title: 'Privacy Policy', href: '/privacy' },
        { title: 'Terms of Service', href: '/terms' },
        { title: '18+ Compliance Notice', href: '/safety' },
      ],
    },
  },
  seo: {
    defaultTitle: 'Adaah — 18+ Private Directory | Hyderabad Companions',
    titleTemplate: '%s | Adaah',
    defaultDescription:
      'Adaah is Hyderabad’s premier 18+ private directory for verified independent companions, VIP models, and escort introductions in Banjara Hills, Jubilee Hills, and Hitech City.',
    keywords: [
      'Adaah',
      'hyderabad companions',
      'banjara hills companions',
      'jubilee hills companions',
      'independent companions hyderabad',
      'verified companions',
      'vip companions hyderabad',
      'discreet companionship hyderabad',
    ],
  },
};
